#!/bin/bash
# nmManualSetup - manual set up while using network manager
# version 2009-01-08
# Copyright Rich Lott
# GNU licence
#
# To install put this script (must be executable) in /etc/network/if-up.d/z_nmManualSetup
# Note the lowercase z is important to make sure it runs last.


function mylog {
	logger nmManualConfig: $@ 
}
function mylogPipe {
	while read l
	do 	
		l="nmManualConfig: $l"
		echo $l
	done | logger
}
function atWork {
	mylog $IFACE ' @ work '
	ifconfig $IFACE 192.168.254.200  2>&1 | mylogPipe
	cat /etc/hosts.main /etc/hosts.work >/etc/hosts
	chmod 644 /etc/hosts
	# kill dhcp
	pkill -f "/sbin/dhclient.*$IFACE" 2>&1 | mylogPipe
	route -n | mylogPipe
	sleep 1
	route add default gw 192.168.254.253  2>&1 | mylogPipe
	route -n | mylogPipe
}
function atHome {
	mylog $IFACE ' @ home'
	ifconfig $IFACE 192.168.1.3  2>&1 | mylogPipe
	cat /etc/hosts.main /etc/hosts.home >/etc/hosts
	chmod 644 /etc/hosts
	# kill dhcp
	pkill -f "/sbin/dhclient.*$IFACE" 2>&1 | mylogPipe
	route -n | mylogPipe
	sleep 1
	route add default gw 192.168.1.1  2>&1 | mylogPipe
	route -n | mylogPipe
	cp /etc/resolv.conf.general /etc/resolv.conf
}
function getGwMacAddress
{
	gwIp=$(route -n | grep ^0 | perl -pe 's/^.*?\s+([.0-9]+).*$/$1/')
	ping -c1 $gwIp >/dev/null 2>/dev/null
	mac=$(fgrep $gwIp /proc/net/arp | perl -pe 'split /\s+/; $_=$_[3];')
	mylog "Mac address of gw: $mac"
	echo $mac;
}

# default hosts file
cp /etc/hosts.main /etc/hosts
chmod 644 /etc/hosts

if [[ "$IFACE" == "wlan0" ]]
then
	if iwconfig $IFACE 2>/dev/null | grep peopleplanet >/dev/null 2>&1
	then
		atWork 
	elif iwconfig $IFACE 2>/dev/null | grep smiles >/dev/null 2>&1
	then
		atHome
	else
		mylog $IFACE ' @ unknown -- no action taken.'
	fi
elif [[ "$IFACE" == "eth0" ]]
then

	case `getGwMacAddress` in
	'00:1B:2F:78:B2:34') atWork
		;;
	'00:11:95:94:AA:9F') atHome
		;;
	*) 
		mylog $IFACE ' @ unknown -- no action taken.'
	esac
else
		mylog $IFACE ' @ unknown -- no action taken.'
fi

exit 0
