#!/bin/bash
SECRETS=/home/rich/encrypted.img
NAME=enc
LOOP=/dev/loop1

if mount | grep /mnt/$NAME >/dev/null
then
	sudo umount /mnt/$NAME
else
	echo "not mounted according to mount"
fi
if [ -e /dev/mapper/$NAME ]
then
	echo "(Will need sudo password to lock)"
	sudo cryptsetup remove $NAME
	sudo losetup -d $LOOP
else
	echo "Not unlocked."
fi
