#!/bin/bash
if mount | grep /mnt/secrets >/dev/null
then
	umount /mnt/secrets
else
	echo "not mounted according to mount"
fi
if [ -e /dev/mapper/secrets ]
then
	echo "Will need sudo password to lock"
	sudo cryptsetup remove secrets
else
	echo "Not unlocked."
fi
