#!/bin/bash
SECRETS=/home/rich/Dropbox/secrets
if mount | grep /mnt/secrets >/dev/null
then
	echo "Already mounted"
	exit
fi

if sudo losetup /dev/loop0 2>/dev/null | grep $SECRETS >/dev/null
then
	echo "Loop already set up."
else
	echo -n "setting up loop..."
	sudo losetup /dev/loop0 $SECRETS
	echo "done"
fi
if [ ! -e /dev/mapper/secrets ]
then
	echo "Opening..."
	sudo cryptsetup create secrets /dev/loop0
fi
sudo mount /dev/mapper/secrets /mnt/secrets

