#!/bin/sh

# kill arts if necessary
artspid=$(ps ax | grep arts[d] | head -1 | perl -pe 's@\s*(\d*).*@$1@')
if [ -n "$artspid" ] ; then kill $artspid ; fi

# kill jack if it's already loaded.
jackdpid=$(ps ax | grep jack[d] | head -1 | perl -pe 's@\s*(\d*).*@$1@')
if [ -n "$jackdpid" ] ; then kill $jackdpid ; fi

# start jack
command=$(<~/.jackdrc)
nice -18 $command &

# don't start arts - kde will do it when it wants to?
# artsd
