#!/bin/bash
if [ "`whoami`" != "root" ] 
then
	echo "you must be root."
	exit 1
fi
cd /home/rich/
rm debs/Packages.gz -f
dpkg-scanpackages debs /dev/null | gzip -9 > debs/Packages.gz
echo Ready. Remember to: apt-get update

