#!/bin/bash
if [ "$1" != '-f' ]
then
	echo "Usage: cms_update_from_bytemark -f [-q]"
	echo ""
	echo "* Copies database 'cms' to **overwrite** local copy"
	echo "  using mysqldump"
	echo "  if -q option supplied stats table is not copied."
	echo "* Copies files in "
	echo "  /dl/ "
	echo "  /cms_graphics/"
	echo "  /wikiResources/"
	echo "  /wikiResourcesOnline/"
	echo "  /gizmo_picpet/"
	echo "  to local dirs using rsync"
	exit 0
fi
if [ "$2" = '-q' ]
then
	quick=' --ignore-table=cms.statsVisitResponses --ignore-table=cms.statsPages --ignore-table=cms.stats '
else
	quick=''
fi
cd /var/www/peopleandplanet.org/ || { echo "could not change to /var/www/peopleandplanet.org/ FAILING."; exit 1; }
LOGFILE=/home/rich/cms_update_from_bytemark.log
date >$LOGFILE # restart log file
echo "Copying 'cms' database..."
echo "Copying 'cms' database..." >>$LOGFILE 
command='mysqldump -upeopleandplanet -p3kfDs~R--a7dSW cms --ignore-table=cms.navigationWip '$quick'  | bzip2'
{ ssh root@bytemark -p22922 "$command" | bunzip2 | mysql -Dcms ; } >>$LOGFILE 2>&1

for d in dl cms_graphics wikiResources wikiResourcesOnline gizmo_picpet
do
	echo "Copying files in $d..."
	echo "Copying files in $d..." >>$LOGFILE
	rsync -auzve 'ssh -p22922' root@bytemark:cms/$d/ $d/ >>$LOGFILE 2>&1
done

echo "done."
echo "done." >>$LOGFILE
