#!/usr/bin/php
<?php
// montage_easy - easier use of "montage"
if (!isset($argv[1]) ||
	$argv[1]=='--help' || 
	$argv[1]=='-h' ) {
	echo <<<EOF
use: montage_easy COLSxROWS [--each] [WIDTHxHEIGHT[+SPACING]] FILES OUTPUTNAME 
where:
	WIDTH and HEIGHT are in mm (300dpi assumed)
	as for SPACING - defaults to 5mm
	if --each specified then the WIDTHxHEIGHT refers to each image, otherwise
		it refers to paper size. ifWIDTHxHEIGHT is not given a4 is assumed.
EOF;
	exit (0);
}

unset( $argv[ 0 ] );
$re1='/^\d+[xX]\d+(\+\d+)?$/i';
$re2='/^\d+[xX]\d+$/i';

$each = false;
$colsxrows = '';
$spacing = 5;
$pageW = 210;
$pageH = 297;
$dpi = 300;

if ( $key=array_search( '--each', $argv ) ) 
{
	$each = true;
	unset( $argv[ $key ] );
}

//find first 123x123 COLSxROWS
foreach ( $argv as $key=>$value )
{
	if ( preg_match( $re1, $value ) ) 
	{
		unset( $argv[ $key ] );
		
		if ( $colsxrows == '' ) 
		{	
			$colsxrows = $value;
			$tmp = preg_split( '/[xX]/', $colsxrows );
			$cols = $tmp[0];
			$rows = $tmp[1];
		}
		else 
		{
			// geometry given
			$geometry = preg_split('/[\+xX]/',$value);
			print_r($geometry);
			if ( $each ) 
			{
				$imgMaxW=$geometry[0];
				$imgMaxH=$geometry[1];
			}
			else
			{
				$pageW=$geometry[0];
				$pageH=$geometry[1];
			}
			if ( isset( $geometry[2] ) ) $spacing=$geometry[2];
		}
	}
}

if ( ! $each )
{
	//calculate max size for each image based on paper size
	$imgMaxW = ( $pageW - $spacing ) / $cols - $spacing;
	$imgMaxH = ( $pageH - $spacing ) / $rows - $spacing;
}

echo "Page: $pageW x $pageH mm at $dpi dpi\n";
echo "Cols: $cols x $rows with $spacing mm spacing\n";
echo "Image size max: $imgMaxW x $imgMaxH mm\n";

$geom = (int)($imgMaxW / 25.4 * $dpi ) . 'x' .
	(int)($imgMaxH / 25.4 * $dpi ) . '+' .
	(int)($spacing / 25.4 * $dpi ) . '+' .
	(int)($spacing / 25.4 * $dpi ) ;
	
$files = '';
foreach ( $argv as $value )	$files .= "\"$value\" ";
exec ("montage -tile $colsxrows -geometry $geom $files");
?>
