#!/usr/bin/perl -w
use strict;

my $usage='';
my $threshold = '90%';
my $bg='white';
if ( $#ARGV <0 
	|| $#ARGV> 2 ) {$usage='Wrong number of arguments.';}
elsif ( ! -f $ARGV[0] ) { $usage="File $ARGV[0] does not exist"; }
elsif ( ! $ARGV[1] =~ m/^(#[0-9A-Fa-f]{3,6}|white|black|gray)$/ ) { $usage='Colour doesn\'t match'; }
elsif ( $#ARGV==2 
		&& ! $ARGV[2] =~ m/^\d+%$/ ) { $usage=$ARGV[2] .' is not like 83%'; }
die(<<EOF
Usage: $0 inputfile backgroundColour [threshold]
	where threshold of 80% would mean make all 
	pixels fully transparent if they are more than 
	80% transparent. Default: 90%
$usage

EOF
	) if ($usage);

$threshold = $ARGV[2] if ($#ARGV == 2);
$bg = $ARGV[1] if ($#ARGV >= 1);

my $filename = $ARGV[0];
$filename =~ s/"/\\"/g;
my $newfilename = $filename;
$newfilename =~ s/(^.*)(\..*?)$/$1.gif/;

my $imCmd='convert "' . $filename . 
	'" +repage \( +clone +matte -matte -channel matte -threshold -1 +channel \) ' .
	'+swap \( +clone -background "' . $bg . '" -flatten \) +swap ' . 
	'\( +clone -channel matte -separate +channel +matte -threshold ' . 
	$threshold . ' -negate \) -delete -2 -composite "' . $newfilename .'"';
print "$imCmd\n";
system($imCmd);
