#!/usr/bin/env python
#
# by desgua
#
# To minimize with unity Launcher
#
# note: it wont work if multiple windows
# from the same app are open
#
##################################
import os
import wnck
import gtk
stream = os.popen("xdotool click --clearmodifiers 1")
screen = wnck.screen_get_default()

while gtk.events_pending():
    gtk.main_iteration()

windows = screen.get_windows()
active = screen.get_active_window()

for w in windows:
    if w == active:
        w.minimize()
