#!/usr/bin/perl -w
use strict;

my @photos=();

my $pageCount=1;

my ($noprint, $a5, $shouldBePortrait, $eachPixWide, $eachPixTall) = (0, 0, 1, 300*210/2/25.4, 300*297/2/25.4);
$eachPixWide = int $eachPixWide;
$eachPixTall = int $eachPixTall;
while ($_ = shift @ARGV)
{
	if ( m/^--a5/)
	{
		# a5 not a6.
		$a5=1;
		$shouldBePortrait = 0;
		$eachPixWide = 300*210/25.4;
		$eachPixTall = 300*297/25.4/2;
		print STDERR "a5 not implemented yet!\n";
	}
	if ( m/^--noprint/)
	{
		# don't pass files to kprinter at end; just make pages and leave them.
		$noprint = 1;
	}
	elsif ( m/^-/ ) {
		print "unknown option $_\n ";
	}
	else
	{
	       	push @photos,$_ ;
	}
}

# get dir for first photo.
$_ = $photos[0];
my $cwd=`pwd`;
chdir $1 if ( m{^(.+/)(.+)$} );
print "changing to $1\n" if ( m{^(.+/)(.+)$} );

my $perPage = $a5?2:4;

while ($#photos>-1)
{
	my @photos4=();
	push @photos4, (shift @photos) for (1 .. 4);
	my $count=0;
	while (++$count<=$perPage)
	{
		$_ = shift @photos4;
		my $singleQuotedFileName=$_;
		if ((! $_) && ($count==1))
		{ 
			system( "convert -size ${eachPixWide}x${eachPixTall} xc:white temp$count.miff"); 
			next;
		}
		if (! $_ )
		{
			system("ln","-s","temp" . ($count-1) . ".miff", "temp$count.miff");
			next;
		}
		else 
		{
			$singleQuotedFileName =~ s/'/'\\''/;
		}
		print "preparing $_ with xxjpeginfo \'$singleQuotedFileName\'|xx ";
		open FH, "jpeginfo \'$singleQuotedFileName\'|" or die("$_ doesn't exist!\n");
		my $info = <FH>;
		close FH;
		$info =~ m/\s(\d+) x (\d+)\s/;
		my @cmd = qw|convert|;
		if (($1/$2<=1) != $shouldBePortrait)
		{
			push @cmd, ('-size', "${eachPixTall}x${eachPixWide}");
			push @cmd, qw|-rotate 90| 
		}
		else
		{
			push @cmd, ('-size', "${eachPixWide}x${eachPixTall}");
		}
		push @cmd, $_;
		push @cmd, ('-resize', "${eachPixWide}x${eachPixTall}>", "temp$count.miff");
		print "...\n";
#print "preparing $_: " . join(' ',@cmd) . "\n";
		system @cmd;
	}
	print "Doing page $pageCount.";
	if ( $a5 )
	{
		system ("convert","temp1.miff","temp2.miff", "-append","page_" . $pageCount++ . ".jpg");
	}
	else
	{
		system ("convert","temp1.miff","temp2.miff", "-append", "temp5.miff");
		print ".";
		system ("convert","temp3.miff","temp4.miff", "-append", "temp6.miff");
		print ".";
		system ("convert","temp5.miff","temp6.miff", "+append", "page_" . $pageCount++ . ".jpg");
	}
	print ".\n";
	unlink (glob "temp*.miff");
}

# stop here if not printing
die() if ($noprint);

# otherwise pass pages to kprinter
system("kprinter page_*.jpg");

print "would now delete pages\n";
