#!/usr/bin/perl -w
use strict;
# version 19 nov 2005 11:40
print "Warning: playlists will be added together\n" if ( $#ARGV >0 );
die "Usage: playlistmangle <playlist.m3u>\n" if ( $#ARGV == -1 );

my ($lookfor, $replacewith, $filename,$prefix)=('','',$ARGV[0] );

while (<>)
{
	next if /^#/;
	if ( $lookfor eq '' )
	{
		# check for old laptop files -> new laptop files
		if ( m!^/root/rich! )
		{
			$lookfor='/root/rich';
			$replacewith='/home/bulk';
			$prefix = 'laptop_';
		}
		# check for new laptop files -> home files
		elsif ( m!^/home/bulk! )
		{
			$lookfor='/home/bulk';
			$replacewith='/mnt/bulk';
			$prefix = 'home_';
		}
		# must be a home file
		else
		{
			$lookfor='/mnt/bulk';
			$replacewith='/home/bulk';
			$prefix = 'laptop_';
		}
		open (OUT, ">$prefix$filename" );
		select OUT;
	}
	s!^$lookfor!$replacewith!;
	print $_;
}
print STDOUT "Written $prefix$filename\n";
