#!/bin/bash
# input from kmail
# saves std in to a new file beginning with prefix
outputfile='/home/rich/testout';
folder=${1:-'/home/rich/'}
prefix=${2:-'unknown'}
cd "$folder"
fileno=`ls "$prefix"* 2>/dev/null | tail -n1 ` 
fileno=${fileno#"$prefix"}
fileno=${fileno:-0}
fileno=`expr "$fileno" : '0\+\([1-9][0-9]\+\)'`
 
#while [[ "${fileno:0:1}" = "0" ]]
#do fileno=${fileno:1}
#done
#echo now $fileno
fileno=$(($fileno+1))
fileno=`printf %05i $fileno`
#echo $fileno
cat >>$prefix$fileno
