#!/bin/bash
#reads email on stdin
tempfile=/tmp/spamkiller
spam=0
while read a
do	echo "$a" 
done >$tempfile
if fgrep "Update on your" $tempfile
then echo "X-rich: naaa"
fi
cat $tempfile
rm $tempfile -f

