#!/bin/bash

cmd="$@"

if [ "x$cmd" = "x" -o "x$cmd" = "x--help" -o "x$cmd" = "x-h" ]
then 	echo "Usage: $0 command [args]"
	echo "runs the command you give whenever any file in the directory changes."
	echo "Nb. if the args include a filename glob you must escape them "
	echo "    if you want them to be evaluated each time. Otherwise they will"
	echo "    get expanded once."
	echo ""
	exit
fi

a=$(stat * | md5sum)
while sleep 1 
do 
	b=$(stat * | md5sum)
	if [ "$b" != "$a" ]
	then 
		echo "directory changed at " $(date) " running: $cmd"
		$cmd
		# re-run md5 of stat to avoid infinite loop generated if cmd itself changes the directory!
		b=$(stat * | md5sum)
		a="$b"
	fi
done
