#!/usr/bin/perl -w
use strict;
# version 19 nov 2005 11:40

die "Usage: playlist_check <playlist.m3u>\n" if ( $#ARGV == -1 );

my $dirs =1;
if ( $ARGV[0] eq '-f' ) { $dirs = 0; shift } 

die "Usage: playlist_check <playlist.m3u>\n" if ( $#ARGV == -1 );


my %hash = ();

while (<>)
{
	next if /^#/;
	chomp;
	s{^(.+)/.*?$}{$1} if ( $dirs );
	$hash{ $_ } = 1 if ( ! -e $_ );
}
print "Missing " . ($dirs?'directory':'file') . " $_\n" foreach ( keys( %hash ) );
