#!/usr/bin/php
<?php
/* remove lines found in one file from another.
*/
if (!($toremove = file( $argv[1] ))) {
	fwrite(STDERR,"Cannot open $argv[1]\n");
	exit;
}
if (!($removefrom = file( $argv[2] ))) {
	fwrite(STDERR,"Cannot open $argv[2]\n");
	exit;
}
$out= str_replace( $toremove, '', $removefrom);
foreach ($out as $key=>$val) if ($val!='' && $val!="\n") fwrite(STDOUT, $val); 
?>
