#!/usr/bin/php
<?php
/* remove lines found in one file from another.
*/
$toremove = explode("\n",file_get_contents($argv[1]));
$toremove = array_flip($toremove);

$removefrom = explode("\n",file_get_contents($argv[2]));
foreach ($removefrom as $_)
	if (!array_key_exists($_, $toremove)) echo "$_\n";
?>
