#!/bin/bash
#script to wait for execution of various pids to finish

while [ -n "$1" ]
do
msg="`date` : pid$1 not finished..."
	while [ -e /proc/$1/ ] 
	do 	echo -n "$msg"
		msg=""
		sleep 1
		done
	echo "finished (" `date` ")"
	shift
done
echo "all done."
