#!/bin/bash
#wrapper for convert
if [ $# -lt 2 ]
then	echo "Use: $0 [-]degrees files"
	echo "rotates each image by degrees. REPLACES original image."
	echo ""
	exit 0
fi

rotate="$1"
shift

while [ "x$1" != "x" ]
do
	if [ -f "$1" -a -w "$1" -a -r "$1" ]
	then
		echo "rotating $1"
		convert -rotate "$rotate" "$1" "$1"
	else
		echo "Warning: Could not change $1" >&2
	fi
	shift
done
